<a href="https://colab.research.google.com/github/RMoulla/PBD_Octobre/blob/main/Tuto_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial Python

## Première commande

In [ ]:
print("Hello word")

Hello word


## Structure conditionnelle

In [ ]:
nom = ''
if nom == "Alice":
    print("Salut Alice!")
else:
    print("Salut camarade !")

Salut camarade !


## Boucles

In [ ]:
for i in range(5):
    print(i**2)

0
1
4
9
16


## Opérations élémentaires

In [ ]:
import math
racine = math.sqrt(16)
print(racine)

4.0


In [ ]:
sinus = math.sin(math.pi/2)
print(sinus)

1.0


In [ ]:
sinus_hyperbolique = math.sinh(1)
print(sinus_hyperbolique)

1.1752011936438014


## Listes

### Créer d'une liste
Les listes sont créées en plaçant les éléments (éléments de la liste) entre crochets, séparés par des virgules.

In [ ]:
ma_liste = [1, 2, 3, 4, 5]
print(ma_liste)

[1, 2, 3, 4, 5]


### Accéder aux éléments d'une liste

On peut accéder aux éléments d'une liste en se référant à l'index.

In [ ]:
print(ma_liste[0])  # Affiche 1
print(ma_liste[3])  # Affiche 3
print(ma_liste[-1]) # Affiche le dernier élément, 5

1
4
5


### Modifier un élément

On peut modifier un élément d'une liste à l'aide de son index.

In [ ]:
ma_liste[2] = 33
print(ma_liste)

[1, 2, 33, 4, 5]


### Ajouter des éléments

In [ ]:
# Utiliser append pour ajouter à la fin
ma_liste.append(6)
print(ma_liste)
# Utiliser insert pour ajouter à une position spécifique
ma_liste.insert(1, 1.5)  # Ajoute 1.5 à la position 1
print(ma_liste)

[1, 2, 33, 4, 5, 6]
[1, 1.5, 2, 33, 4, 5, 6]


### Supprimer des éléments

In [ ]:
# Supprimer un élément à un index spécifique
del ma_liste[1]

# Supprimer un élément spécifique (la première occurrence)
ma_liste.remove(33)

# Supprimer et retourner le dernier élément
ma_liste.pop()

6

In [ ]:
print(ma_liste)

[1, 2, 4, 5]


### Etendre une liste

In [ ]:
autre_liste = [7, 8, 9]
ma_liste.extend(autre_liste)
print(ma_liste)

[1, 2, 4, 5, 7, 8, 9]


### Identifier l'index d'un élément

In [ ]:
index = ma_liste.index(4)
print(index)  # Affiche l'index de la première occurrence de 4

2


### Trier une liste

In [ ]:
ma_liste.sort()        # Trier en ordre croissant
print(ma_liste)
ma_liste.sort(reverse=True) # Trier en ordre décroissant
print(ma_liste)

[1, 2, 4, 5, 7, 8, 9]
[9, 8, 7, 5, 4, 2, 1]


### List comprehension

In [ ]:
carrés = [x**2 for x in range(10)]
print(carrés)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


### Copier une liste

In [ ]:
copie = ma_liste.copy()
print(copie)

[9, 8, 7, 5, 4, 2, 1]


### Vider une liste

In [ ]:
ma_liste.clear()

In [ ]:
liste2 = [2, "chat", "poisson", 4]
for elem in liste2:
  print(elem)

2
chat
poisson
4


## Dictionnaires

### Créer un dictionnaire

In [ ]:
val_clé_dict = {"clé1": "valeur1", "clé2": "valeur2", "clé3": "valeur3"}
print(val_clé_dict)

{'clé1': 'valeur1', 'clé2': 'valeur2', 'clé3': 'valeur3'}


### Créer un dictionnaire à partir de listes

In [ ]:
list1 = ["Tom", "Alice", "Bob"]
list2 = [42, 30, 35]
mon_dict = dict(zip(list1, list2))
print(mon_dict)

{'Tom': 42, 'Alice': 30, 'Bob': 35}


### Accéder à une valeur par sa clé

In [ ]:
valeur = mon_dict["Alice"]
print(valeur)

30


### Ajouter ou modifier des éléments

In [ ]:
mon_dict["Bob"] = 45
print(mon_dict["Bob"])
mon_dict["Anna"] = 36
print(mon_dict)

45
{'Tom': 42, 'Alice': 30, 'Bob': 45, 'Anna': 36}


### Supprimer un élément

In [ ]:
del mon_dict["Anna"]
print(mon_dict)

{'Tom': 42, 'Alice': 30, 'Bob': 45}


### Obtenir les clés, les valeurs, et les paires clé-valeur

In [ ]:
clés = mon_dict.keys()
print(clés)
valeurs = mon_dict.values()
print(valeurs)
paires = mon_dict.items()
print(paires)

dict_keys(['Tom', 'Alice', 'Bob'])
dict_values([42, 30, 45])
dict_items([('Tom', 42), ('Alice', 30), ('Bob', 45)])


### Fusionner deux dictionnaires


In [ ]:
dict2 = {"Aline": 25, "Théo": 22}
mon_dict.update(dict2)
print(mon_dict)

{'Tom': 42, 'Alice': 30, 'Bob': 45, 'Aline': 25, 'Théo': 22}


### Dictionnaire comprehension

In [ ]:
carrés = {x: x**2 for x in (2, 4, 6)}
print(carrés)

{2: 4, 4: 16, 6: 36}


### Copier un dictionnaire



In [ ]:
copie_dict = mon_dict.copy()
print(copie_dict)

{'Tom': 42, 'Alice': 30, 'Bob': 45, 'Aline': 25, 'Théo': 22}


## Tableaux

### Créer un tableau

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2]
 [3 4]
 [5 6]]


### Accéder aux éléments d'un tableau

In [ ]:
print(arr1[1])
print(arr2[1])

2
[3 4]


### Slicing

In [ ]:
print(arr1[1:3])
print(arr2[:,1])

[2 3]
[2 4 6]


### Quelques propriétés des tableaux

In [ ]:
shape = arr2.shape
print(shape)        # Dimensions du tableau (nombre de lignes, nombre de colonnes)
size = arr2.size          # Nombre total d'éléments
print(size)
atype = arr1.dtype         # Type de données des éléments
print(atype)

(3, 2)
6
int64


### Opérations sur les tableaux

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr_sum = arr1 + 10                  # Ajoute 10 à chaque élément
print(arr_sum)
product = np.dot(arr1, arr1)         # Produit scalaire de arr1 avec lui-même
print(product)
multiply = arr1 * arr1              # Multiplie chaque élément par lui-même
print(multiply)

[11 12 13 14 15]
55
[ 1  4  9 16 25]


### Quelques tableaux par défaut

In [ ]:
arr_zeros = np.zeros(5)              # Tableau de 5 zéros
print(arr_zeros)
arr_ones = np.ones((3, 2))           # Tableau 3x2 de uns
print(arr_ones)
arr_range = np.arange(0, 10, 2)      # Tableau [0, 2, 4, 6, 8]
arr_linspace = np.linspace(0, 1, 5)  # Tableau [0, 0.25, 0.5, 0.75, 1]

[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


### Manipulation des formes

In [ ]:
arr_flatten = arr2.flatten()      # Convertit en un tableau 1D
print(arr_flatten)
arr_reshape = arr1.reshape(5, 1)   # Reshape en colonne 5x1

[1 2 3 4 5 6]


## DataFrames


### Créer un DataFrame

In [ ]:
import pandas as pd

data = {
    'Nom': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Ville': ['Paris', 'Lyon', 'Marseille']
}

df = pd.DataFrame(data)
print(df)

       Nom  Age      Ville
0    Alice   25      Paris
1      Bob   30       Lyon
2  Charlie   35  Marseille


### Sélectionner des donnée

In [ ]:
# Colonnes
noms = df['Nom']
subset = df[['Nom', 'Age']]

# Lignes
ligne_2 = df.iloc[1]  # Par index numérique
ligne_bob = df[df['Nom'] == 'Bob']  # Par condition

# Combinaisons
cellule = df.at[1, 'Nom']  # Valeur de la cellule ligne 2, colonne "Nom"
print(cellule)

Bob


### Manipulation des données

In [ ]:
# Ajouter une colonne
df['Profession'] = ['Ingénieur', 'Médecin', 'Avocat']

# Supprimer une colonne
df = df.drop(columns=['Profession'])

# Renommer les colonnes
df = df.rename(columns={'Nom': 'Prénom'})

# Trier
df = df.sort_values(by='Age', ascending=False)

### Gérer les données manquantes

In [ ]:
# Supprimer les lignes avec des données manquantes
df = df.dropna()

# Remplacer les données manquantes
df = df.fillna(value=0)

### Fonctions d'agrégation

In [ ]:
moyenne_age = df['Age'].mean()
print(moyenne_age)
total = df['Age'].sum()
print(total)

30.0
90


### Ajouter une ligne

In [ ]:
nouvelle_ligne = pd.DataFrame({
    'Prénom': ['David'],
    'Age': [40],
    'Ville': ['Marseille']
})

df = pd.concat([df, nouvelle_ligne])
print(df)

    Prénom  Age      Ville
2  Charlie   35  Marseille
1      Bob   30       Lyon
0    Alice   25      Paris
0    David   40  Marseille


### Grouper des données

In [ ]:
grouped = df.groupby('Ville').sum()
print(grouped)

           Age
Ville         
Lyon        30
Marseille   75
Paris       25


<ipython-input-106-37df70100e6e>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  grouped = df.groupby('Ville').sum()


### Sauvegarder un DataFrame

In [ ]:
df.to_csv('mon_nouveau_fichier.csv', index=False)
df.to_excel('mon_nouveau_fichier.xlsx', index=False)